---
version: '3'
services:
  plugin_test:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
  plugin_lint:
    image: buildkite/plugin-linter:latest
    command: ['--id', 'monebag/monorepo-diff']
    volumes:
      - ".:/plugin"
